- block:
    - name: Template | Nginx deny config
      template:
        src: files/deny.conf.j2
        dest: /etc/nginx/acl/deny.conf
        owner: root
        mode: '0644'
        backup: true
      register: copy_result
      become: yes
      notify:
        - Test Nginx

    - name: Flush handlers after copy
      meta: flush_handlers

  rescue:
    - name: Restore backup
      ansible.builtin.copy:
        src: "{{ copy_result.backup_file }}"
        dest: /etc/nginx/acl/deny.conf
        remote_src: true
      when: copy_result.backup_file is defined
      become: yes
      notify:
        - Test Nginx

    - name: Flush handlers after restore
      meta: flush_handlers

  always:
    - name: Cleanup | Remove deny.conf backup
      file:
        path: "{{ copy_result.backup_file }}"
        state: absent
      when: copy_result.backup_file is defined
      become: yes
      failed_when: false
